@base_url=http://localhost:3000/api

### register
POST {{base_url}}/users/register
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "1234567t"
}

### login
POST {{base_url}}/users/login
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "1234567t"
}

###
GET {{base_url}}/application

###
GET {{base_url}}/url?appId=1f818cdb-2964-480c-af2d-0d325077bf49

###
GET {{base_url}}/url?appId=1f818cdb-2964-480c-af2d-0d325077bf49&shortId=2hdn1