@base_url=http://localhost:3000/api

### register
POST {{base_url}}/users/register
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "1234567t"
}

### login
POST {{base_url}}/users/login
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "1234567t"
}

###
GET {{base_url}}/application